### ISSUE TITLE
Request: Optionally Create branch

### ISSUE THREAD

**Issue by bsamaripa** [ezweave/what-name-branch#10]
As a lazy user, I would like to be able to automatically create a branch based on the name I just generated so that I can get to work faster.

### Acceptance Criteria: 
* Extra page step to offer to create new branch using new name
* Following selecting yes, allow to choose which branch to branch-off from (e.g. main, develop, etc)
* Last step to offer to checkout this branch

### Considerations
* What to do with unstaged changes? Stash and report stash number?
* How to handle stale local branches?

**Comment by ezweave** [comment]
Fixed in 1.1.10.
